name: Tests
run-name: "Running tests on: ${{ github.ref_name }} ðŸš€"
on: [push]

runs-on: ubuntu-latest

env:
  NODE_ENV: "test"

defaults:
  run:
    working-directory: ./src

jobs:
  Node-Setup:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: "src/.nvmrc"
          cache: "npm"
          cache-dependency-path: "src/package-lock.json"

      - name: Install packages
        run: npm ci

  Test-Unit:
    needs: Node-Setup
    steps:
      - name: Run unit tests
        run: npm run test-unitCI

  Test-Integration:
    needs: Node-Setup
    steps:
      - name: Run integration tests
        run: npm run integration
